# Generated by Django 6.0.3 on 2026-03-26 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0005_bill_document_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone_number', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('broadcast', 'Broadcast'), ('digest', 'Digest'), ('milestone', 'Milestone'), ('reply', 'Reply'), ('reminder', 'Reminder')], max_length=16)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('provider', models.CharField(default='africastalking', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='africastalking', max_length=32)),
                ('event_type', models.CharField(choices=[('sms_inbound', 'SMS inbound'), ('sms_delivery_report', 'SMS delivery report'), ('ussd', 'USSD')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('raw_phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='processed', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='cadence',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('milestone', 'Milestone')], default='instant', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='consent_source',
            field=models.CharField(choices=[('sms', 'SMS'), ('ussd', 'USSD'), ('admin', 'Admin'), ('api', 'API')], default='api', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='consented_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_digest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pause_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scope',
            field=models.CharField(choices=[('bill', 'Bill'), ('category', 'Category'), ('county', 'County'), ('sponsor', 'Sponsor'), ('all', 'All bills')], default='bill', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='target_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('sms_broadcast', 'SMS broadcast'), ('sms_inbound', 'SMS inbound'), ('sms_delivery_report', 'SMS delivery report'), ('ussd_hit', 'USSD hit'), ('subscription', 'Subscription'), ('vote', 'Vote'), ('system', 'System'), ('scrape', 'Scrape'), ('message_outbound', 'Message outbound'), ('consent', 'Consent'), ('digest', 'Digest'), ('webhook', 'Webhook')], default='system', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('phone_number', 'channel', 'scope', 'bill', 'target_value'), name='unique_subscription_target_per_phone_channel'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='legislative.bill'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='legislative.subscription'),
        ),
        migrations.AddIndex(
            model_name='webhookreceipt',
            index=models.Index(fields=['provider', 'event_type'], name='legislative_provide_b96bab_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreceipt',
            index=models.Index(fields=['external_id'], name='legislative_externa_674428_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreceipt',
            index=models.Index(fields=['status'], name='legislative_status_ac5dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='legislative_status_1fbc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['recipient_phone_number'], name='legislative_recipie_42c76f_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['message_type'], name='legislative_message_f42c32_idx'),
        ),
    ]
