# Generated by Django 6.0.3 on 2026-03-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0009_bill_document_source_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='document_method',
            field=models.CharField(blank=True, choices=[('text', 'Text extraction'), ('ai', 'AI vision extraction'), ('ocr', 'OCR')], default='', max_length=16),
        ),
    ]
